In [52]:
import numpy as np
import pandas as pd
import os

In [74]:
directory = '/Users/botanovaolga/Desktop/mipt/factorial/Covid_MIPT/Russia_region'

for filename in os.listdir(directory):
    filepath = directory + '/' + filename
    try:
        file = pd.read_csv(filepath)
        file['daily_cases_lag'] = file['total_cases'].shift(periods = 1).fillna(0)
        file['daily_death_lag'] = file['total_death'].shift(periods = 1).fillna(0)
        file['daily_cases'] = file['total_cases'] - file['daily_cases_lag']
        file['total_currently_infected'] = file['total_cases'] - file['cured']
        file['death_per_day'] = file['total_death'] - file['daily_death_lag']
        file = file.drop(columns = ['cured', 'daily_cases_lag', 'daily_death_lag'])
        file.to_csv(filepath, index = False)
    except:
        pass

In [75]:
kemerovo = pd.read_csv(directory +'/Kemerovo region.csv')
kemerovo

,date,total_cases,total_death,daily_cases,total_currently_infected,death_per_day
0,2020-03-15T00:00:00.000Z,2,0,2.0,2,0.0
1,2020-03-16T00:00:00.000Z,2,0,0.0,2,0.0
2,2020-03-17T00:00:00.000Z,2,0,0.0,2,0.0
3,2020-03-18T00:00:00.000Z,2,0,0.0,2,0.0
4,2020-03-19T00:00:00.000Z,2,0,0.0,2,0.0
...,...,...,...,...,...,...
206,2020-10-07T00:00:00.000Z,11025,123,169.0,3138,5.0
207,2020-10-08T00:00:00.000Z,11193,126,168.0,3222,3.0
208,2020-10-09T00:00:00.000Z,11361,133,168.0,3276,7.0
209,2020-10-10T00:00:00.000Z,11530,133,169.0,3382,0.0
210,2020-10-11T00:00:00.000Z,11700,137,170.0,3532,4.0